version: '2'
services:
  developersaltkom-app:
    image: developersaltkom
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://developersaltkom-mariadb:3306/developersaltkom
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
    ports:
      - 8080:8080
  developersaltkom-mariadb:
    extends:
      file: mariadb.yml
      service: developersaltkom-mariadb
